
'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA_DIR=path.join(ROOT,'data'),DB_FILE=path.join(DATA_DIR,'db.json'),UPLOAD_DIR=path.join(ROOT,'uploads');
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(UPLOAD_DIR,{recursive:true});
if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify({users:[],sessions:[],resets:[],logs:[],uploads:[]},null,2));
const PORT=Number(process.env.PORT||8080),NODE_ENV=process.env.NODE_ENV||'development';
const ALLOWED=(process.env.ALLOWED_ORIGIN||'*').split(',').map(s=>s.trim());
let writeQueue=Promise.resolve();
function db(){try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch{return{users:[],sessions:[],resets:[],logs:[],uploads:[]}}}
function save(next){writeQueue=writeQueue.then(async()=>{const tmp=DB_FILE+'.tmp';await fs.promises.writeFile(tmp,JSON.stringify(next,null,2));await fs.promises.rename(tmp,DB_FILE)});return writeQueue}
function id(){return crypto.randomUUID()}
function json(res,status,payload,origin){cors(res,origin);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(JSON.stringify(payload))}
function cors(res,origin){let allow='*';if(ALLOWED[0]!=='*'){allow=ALLOWED.includes(origin)?origin:ALLOWED[0]}res.setHeader('Access-Control-Allow-Origin',allow);res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');res.setHeader('Vary','Origin')}
function readJson(req,max=7*1024*1024){return new Promise((resolve,reject)=>{let n=0,chunks=[];req.on('data',c=>{n+=c.length;if(n>max){reject(Object.assign(new Error('Payload too large'),{status:413}));req.destroy();return}chunks.push(c)});req.on('end',()=>{try{resolve(chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{})}catch{reject(Object.assign(new Error('Invalid JSON'),{status:400}))}});req.on('error',reject)})}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return`${salt}:${hash}`}
function verifyPassword(password,stored){const [salt,hex]=String(stored||'').split(':');if(!salt||!hex)return false;const a=Buffer.from(hex,'hex'),b=crypto.scryptSync(password,salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function newSession(data,userId){const token=crypto.randomBytes(32).toString('base64url');data.sessions.push({token,userId,expiresAt:Date.now()+1000*60*60*24*30});return token}
function userFrom(req,data){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const s=data.sessions.find(x=>x.token===token&&x.expiresAt>Date.now());return s?data.users.find(u=>u.id===s.userId):null}
function publicUser(u){return{username:u.username,email:u.email,profile:u.profile||{}}}
async function sendEmail(to,subject,html){const key=process.env.RESEND_API_KEY,from=process.env.MAIL_FROM;if(!key||!from)return false;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html})});return r.ok}
function sanitizeName(s){return String(s||'file').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100)}
function mimeExt(m){return{'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[m]||''}
function serveStatic(req,res){let p=decodeURIComponent(new URL(req.url,'http://x').pathname);if(p==='/')p='/index.html';const safe=path.normalize(p).replace(/^([.][.][/\\])+/, '');const file=path.join(ROOT,safe);if(!file.startsWith(ROOT))return false;if(!fs.existsSync(file)||!fs.statSync(file).isFile())return false;const ext=path.extname(file).toLowerCase(),type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json; charset=utf-8'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res);return true}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin||'';if(req.method==='OPTIONS'){cors(res,origin);res.writeHead(204);return res.end()}const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/api/')){if(serveStatic(req,res))return;res.writeHead(404);return res.end('Not found')}
 try{
  if(url.pathname==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,service:'berry-vibes-ccd'},origin);
  let data=db();
  if(url.pathname==='/api/auth/signup'&&req.method==='POST'){const b=await readJson(req),username=String(b.username||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(username.length<3)throw Object.assign(new Error('Username must be at least 3 characters.'),{status:400});if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(new Error('Enter a valid email.'),{status:400});if(password.length<8)throw Object.assign(new Error('Password must be at least 8 characters.'),{status:400});if(data.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))throw Object.assign(new Error('That username is already in use.'),{status:409});if(data.users.some(u=>u.email===email))throw Object.assign(new Error('That email already has an account.'),{status:409});const u={id:id(),username,email,passwordHash:hashPassword(password),createdAt:new Date().toISOString(),profile:{name:username,height:62,weight:117.4,reason:'',photo:''}};data.users.push(u);const token=newSession(data,u.id);await save(data);return json(res,201,{token,profile:u.profile,user:publicUser(u)},origin)}
  if(url.pathname==='/api/auth/login'&&req.method==='POST'){const b=await readJson(req),identity=String(b.identity||'').trim().toLowerCase(),u=data.users.find(x=>x.email===identity||x.username.toLowerCase()===identity);if(!u||!verifyPassword(String(b.password||''),u.passwordHash))throw Object.assign(new Error('Invalid username/email or password.'),{status:401});const token=newSession(data,u.id);await save(data);return json(res,200,{token,profile:u.profile,user:publicUser(u)},origin)}
  if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');data.sessions=data.sessions.filter(x=>x.token!==t);await save(data);return json(res,200,{ok:true},origin)}
  if(url.pathname==='/api/auth/forgot-password'&&req.method==='POST'){const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),u=data.users.find(x=>x.email===email);let devCode;if(u){const code=String(crypto.randomInt(100000,1000000));data.resets=data.resets.filter(x=>x.userId!==u.id);data.resets.push({userId:u.id,codeHash:crypto.createHash('sha256').update(code).digest('hex'),expiresAt:Date.now()+15*60*1000});await save(data);const sent=await sendEmail(email,'Berry Vibes CCD password reset',`<h2>Your reset code is ${code}</h2><p>It expires in 15 minutes.</p>`);if(!sent&&NODE_ENV!=='production')devCode=code}return json(res,200,{ok:true,...(devCode?{devCode}:{})},origin)}
  if(url.pathname==='/api/auth/reset-password'&&req.method==='POST'){const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),u=data.users.find(x=>x.email===email);if(!u)throw Object.assign(new Error('Invalid or expired reset code.'),{status:400});const h=crypto.createHash('sha256').update(String(b.code||'')).digest('hex'),r=data.resets.find(x=>x.userId===u.id&&x.codeHash===h&&x.expiresAt>Date.now());if(!r)throw Object.assign(new Error('Invalid or expired reset code.'),{status:400});if(String(b.newPassword||'').length<8)throw Object.assign(new Error('New password must be at least 8 characters.'),{status:400});u.passwordHash=hashPassword(String(b.newPassword));data.resets=data.resets.filter(x=>x.userId!==u.id);data.sessions=data.sessions.filter(x=>x.userId!==u.id);await save(data);return json(res,200,{ok:true},origin)}
  if(url.pathname==='/api/auth/forgot-username'&&req.method==='POST'){const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),u=data.users.find(x=>x.email===email);let devUsername;if(u){const sent=await sendEmail(email,'Your Berry Vibes CCD username',`<h2>Your username is ${u.username}</h2>`);if(!sent&&NODE_ENV!=='production')devUsername=u.username}return json(res,200,{ok:true,...(devUsername?{devUsername}:{})},origin)}
  const user=userFrom(req,data);if(!user)throw Object.assign(new Error('Sign in required.'),{status:401});
  if(url.pathname==='/api/me'&&req.method==='GET')return json(res,200,{user:publicUser(user),profile:user.profile||{}},origin);
  if(url.pathname==='/api/profile'&&req.method==='GET')return json(res,200,{profile:user.profile||{}},origin);
  if(url.pathname==='/api/profile'&&req.method==='PUT'){const b=await readJson(req);user.profile={...(user.profile||{}),name:String(b.name||user.username).slice(0,80),height:Number(b.height)||null,weight:Number(b.weight)||null,reason:String(b.reason||'').slice(0,1000),photo:String(b.photo||'').slice(0,5000)};await save(data);return json(res,200,{profile:user.profile},origin)}
  if(url.pathname==='/api/logs'&&req.method==='GET'){return json(res,200,{logs:data.logs.filter(x=>x.userId===user.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,1000)},origin)}
  if(url.pathname==='/api/logs'&&req.method==='POST'){const b=await readJson(req,512*1024);const row={id:id(),userId:user.id,createdAt:new Date().toISOString(),...b};delete row.userId;row.userId=user.id;data.logs.push(row);await save(data);return json(res,201,{log:row},origin)}
  if(url.pathname==='/api/upload'&&req.method==='POST'){const b=await readJson(req,7*1024*1024),m=String(b.mime||''),ext=mimeExt(m);if(!ext)throw Object.assign(new Error('Upload a JPG, PNG, or WEBP image.'),{status:400});const match=String(b.dataUrl||'').match(/^data:image\/(?:jpeg|png|webp);base64,(.+)$/);if(!match)throw Object.assign(new Error('Invalid image data.'),{status:400});const buf=Buffer.from(match[1],'base64');if(buf.length>5*1024*1024)throw Object.assign(new Error('Image must be 5 MB or smaller.'),{status:413});const name=`${user.id.slice(0,8)}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}.${ext}`;await fs.promises.writeFile(path.join(UPLOAD_DIR,name),buf);const row={id:id(),userId:user.id,name:sanitizeName(b.name),kind:String(b.kind||'image').slice(0,40),url:`/uploads/${name}`,createdAt:new Date().toISOString()};data.uploads.push(row);await save(data);return json(res,201,{url:row.url,upload:row},origin)}
  return json(res,404,{error:'API route not found.'},origin)
 }catch(err){return json(res,err.status||500,{error:err.status?err.message:'Server error.'},origin)}
});
server.listen(PORT,()=>console.log(`Berry Vibes CCD server running on http://localhost:${PORT}`));
